// GHG Emissions Data from Master Dataset
// Scope 1: Fuel & LPG
// Scope 2: Electricity
// Scope 3: Water, Waste, Travel, Food

const emissionsData = [
    // 2020 Data
    { year: 2020, campus: 'CSD', scope: 'Scope 1', category: 'Fuel', value: 1500, unit: 'kg CO2e' },
    { year: 2020, campus: 'CSD', scope: 'Scope 1', category: 'LPG', value: 800, unit: 'kg CO2e' },
    { year: 2020, campus: 'CSD', scope: 'Scope 2', category: 'Electricity', value: 5000, unit: 'kg CO2e' },
    { year: 2020, campus: 'CSD', scope: 'Scope 3', category: 'Water', value: 1200, unit: 'kg CO2e' },
    { year: 2020, campus: 'CSD', scope: 'Scope 3', category: 'Waste', value: 800, unit: 'kg CO2e' },
    { year: 2020, campus: 'CSD', scope: 'Scope 3', category: 'Travel', value: 2100, unit: 'kg CO2e' },
    { year: 2020, campus: 'CSD', scope: 'Scope 3', category: 'Food', value: 900, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Alangilan', scope: 'Scope 1', category: 'Fuel', value: 1200, unit: 'kg CO2e' },
    { year: 2020, campus: 'Alangilan', scope: 'Scope 1', category: 'LPG', value: 600, unit: 'kg CO2e' },
    { year: 2020, campus: 'Alangilan', scope: 'Scope 2', category: 'Electricity', value: 4500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Alangilan', scope: 'Scope 3', category: 'Water', value: 1100, unit: 'kg CO2e' },
    { year: 2020, campus: 'Alangilan', scope: 'Scope 3', category: 'Waste', value: 750, unit: 'kg CO2e' },
    { year: 2020, campus: 'Alangilan', scope: 'Scope 3', category: 'Travel', value: 1800, unit: 'kg CO2e' },
    { year: 2020, campus: 'Alangilan', scope: 'Scope 3', category: 'Food', value: 850, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Lipa', scope: 'Scope 1', category: 'Fuel', value: 2000, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lipa', scope: 'Scope 1', category: 'LPG', value: 1000, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lipa', scope: 'Scope 2', category: 'Electricity', value: 6500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lipa', scope: 'Scope 3', category: 'Water', value: 1500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lipa', scope: 'Scope 3', category: 'Waste', value: 1000, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lipa', scope: 'Scope 3', category: 'Travel', value: 2500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lipa', scope: 'Scope 3', category: 'Food', value: 1200, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Balayan', scope: 'Scope 1', category: 'Fuel', value: 800, unit: 'kg CO2e' },
    { year: 2020, campus: 'Balayan', scope: 'Scope 1', category: 'LPG', value: 400, unit: 'kg CO2e' },
    { year: 2020, campus: 'Balayan', scope: 'Scope 2', category: 'Electricity', value: 3000, unit: 'kg CO2e' },
    { year: 2020, campus: 'Balayan', scope: 'Scope 3', category: 'Water', value: 600, unit: 'kg CO2e' },
    { year: 2020, campus: 'Balayan', scope: 'Scope 3', category: 'Waste', value: 400, unit: 'kg CO2e' },
    { year: 2020, campus: 'Balayan', scope: 'Scope 3', category: 'Travel', value: 900, unit: 'kg CO2e' },
    { year: 2020, campus: 'Balayan', scope: 'Scope 3', category: 'Food', value: 500, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Malvar', scope: 'Scope 1', category: 'Fuel', value: 900, unit: 'kg CO2e' },
    { year: 2020, campus: 'Malvar', scope: 'Scope 1', category: 'LPG', value: 450, unit: 'kg CO2e' },
    { year: 2020, campus: 'Malvar', scope: 'Scope 2', category: 'Electricity', value: 3200, unit: 'kg CO2e' },
    { year: 2020, campus: 'Malvar', scope: 'Scope 3', category: 'Water', value: 700, unit: 'kg CO2e' },
    { year: 2020, campus: 'Malvar', scope: 'Scope 3', category: 'Waste', value: 500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Malvar', scope: 'Scope 3', category: 'Travel', value: 1100, unit: 'kg CO2e' },
    { year: 2020, campus: 'Malvar', scope: 'Scope 3', category: 'Food', value: 600, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Lemery', scope: 'Scope 1', category: 'Fuel', value: 1100, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lemery', scope: 'Scope 1', category: 'LPG', value: 550, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lemery', scope: 'Scope 2', category: 'Electricity', value: 3800, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lemery', scope: 'Scope 3', category: 'Water', value: 800, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lemery', scope: 'Scope 3', category: 'Waste', value: 600, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lemery', scope: 'Scope 3', category: 'Travel', value: 1300, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lemery', scope: 'Scope 3', category: 'Food', value: 700, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Lobo', scope: 'Scope 1', category: 'Fuel', value: 700, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lobo', scope: 'Scope 1', category: 'LPG', value: 350, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lobo', scope: 'Scope 2', category: 'Electricity', value: 2500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lobo', scope: 'Scope 3', category: 'Water', value: 500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lobo', scope: 'Scope 3', category: 'Waste', value: 300, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lobo', scope: 'Scope 3', category: 'Travel', value: 700, unit: 'kg CO2e' },
    { year: 2020, campus: 'Lobo', scope: 'Scope 3', category: 'Food', value: 400, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Nasugbu', scope: 'Scope 1', category: 'Fuel', value: 1300, unit: 'kg CO2e' },
    { year: 2020, campus: 'Nasugbu', scope: 'Scope 1', category: 'LPG', value: 650, unit: 'kg CO2e' },
    { year: 2020, campus: 'Nasugbu', scope: 'Scope 2', category: 'Electricity', value: 4200, unit: 'kg CO2e' },
    { year: 2020, campus: 'Nasugbu', scope: 'Scope 3', category: 'Water', value: 900, unit: 'kg CO2e' },
    { year: 2020, campus: 'Nasugbu', scope: 'Scope 3', category: 'Waste', value: 700, unit: 'kg CO2e' },
    { year: 2020, campus: 'Nasugbu', scope: 'Scope 3', category: 'Travel', value: 1600, unit: 'kg CO2e' },
    { year: 2020, campus: 'Nasugbu', scope: 'Scope 3', category: 'Food', value: 800, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Mabini', scope: 'Scope 1', category: 'Fuel', value: 1000, unit: 'kg CO2e' },
    { year: 2020, campus: 'Mabini', scope: 'Scope 1', category: 'LPG', value: 500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Mabini', scope: 'Scope 2', category: 'Electricity', value: 3500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Mabini', scope: 'Scope 3', category: 'Water', value: 750, unit: 'kg CO2e' },
    { year: 2020, campus: 'Mabini', scope: 'Scope 3', category: 'Waste', value: 550, unit: 'kg CO2e' },
    { year: 2020, campus: 'Mabini', scope: 'Scope 3', category: 'Travel', value: 1400, unit: 'kg CO2e' },
    { year: 2020, campus: 'Mabini', scope: 'Scope 3', category: 'Food', value: 700, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'Fuel', value: 850, unit: 'kg CO2e' },
    { year: 2020, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'LPG', value: 425, unit: 'kg CO2e' },
    { year: 2020, campus: 'Pablo Borbon', scope: 'Scope 2', category: 'Electricity', value: 3100, unit: 'kg CO2e' },
    { year: 2020, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Water', value: 650, unit: 'kg CO2e' },
    { year: 2020, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Waste', value: 450, unit: 'kg CO2e' },
    { year: 2020, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Travel', value: 1000, unit: 'kg CO2e' },
    { year: 2020, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Food', value: 550, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'Rosario', scope: 'Scope 1', category: 'Fuel', value: 950, unit: 'kg CO2e' },
    { year: 2020, campus: 'Rosario', scope: 'Scope 1', category: 'LPG', value: 475, unit: 'kg CO2e' },
    { year: 2020, campus: 'Rosario', scope: 'Scope 2', category: 'Electricity', value: 3400, unit: 'kg CO2e' },
    { year: 2020, campus: 'Rosario', scope: 'Scope 3', category: 'Water', value: 700, unit: 'kg CO2e' },
    { year: 2020, campus: 'Rosario', scope: 'Scope 3', category: 'Waste', value: 500, unit: 'kg CO2e' },
    { year: 2020, campus: 'Rosario', scope: 'Scope 3', category: 'Travel', value: 1200, unit: 'kg CO2e' },
    { year: 2020, campus: 'Rosario', scope: 'Scope 3', category: 'Food', value: 650, unit: 'kg CO2e' },
    
    { year: 2020, campus: 'San Juan', scope: 'Scope 1', category: 'Fuel', value: 1100, unit: 'kg CO2e' },
    { year: 2020, campus: 'San Juan', scope: 'Scope 1', category: 'LPG', value: 550, unit: 'kg CO2e' },
    { year: 2020, campus: 'San Juan', scope: 'Scope 2', category: 'Electricity', value: 3900, unit: 'kg CO2e' },
    { year: 2020, campus: 'San Juan', scope: 'Scope 3', category: 'Water', value: 800, unit: 'kg CO2e' },
    { year: 2020, campus: 'San Juan', scope: 'Scope 3', category: 'Waste', value: 600, unit: 'kg CO2e' },
    { year: 2020, campus: 'San Juan', scope: 'Scope 3', category: 'Travel', value: 1500, unit: 'kg CO2e' },
    { year: 2020, campus: 'San Juan', scope: 'Scope 3', category: 'Food', value: 750, unit: 'kg CO2e' },
    
    // 2021 Data
    { year: 2021, campus: 'CSD', scope: 'Scope 1', category: 'Fuel', value: 1600, unit: 'kg CO2e' },
    { year: 2021, campus: 'CSD', scope: 'Scope 1', category: 'LPG', value: 850, unit: 'kg CO2e' },
    { year: 2021, campus: 'CSD', scope: 'Scope 2', category: 'Electricity', value: 5200, unit: 'kg CO2e' },
    { year: 2021, campus: 'CSD', scope: 'Scope 3', category: 'Water', value: 1300, unit: 'kg CO2e' },
    { year: 2021, campus: 'CSD', scope: 'Scope 3', category: 'Waste', value: 900, unit: 'kg CO2e' },
    { year: 2021, campus: 'CSD', scope: 'Scope 3', category: 'Travel', value: 2300, unit: 'kg CO2e' },
    { year: 2021, campus: 'CSD', scope: 'Scope 3', category: 'Food', value: 1000, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Alangilan', scope: 'Scope 1', category: 'Fuel', value: 1300, unit: 'kg CO2e' },
    { year: 2021, campus: 'Alangilan', scope: 'Scope 1', category: 'LPG', value: 650, unit: 'kg CO2e' },
    { year: 2021, campus: 'Alangilan', scope: 'Scope 2', category: 'Electricity', value: 4700, unit: 'kg CO2e' },
    { year: 2021, campus: 'Alangilan', scope: 'Scope 3', category: 'Water', value: 1200, unit: 'kg CO2e' },
    { year: 2021, campus: 'Alangilan', scope: 'Scope 3', category: 'Waste', value: 850, unit: 'kg CO2e' },
    { year: 2021, campus: 'Alangilan', scope: 'Scope 3', category: 'Travel', value: 2000, unit: 'kg CO2e' },
    { year: 2021, campus: 'Alangilan', scope: 'Scope 3', category: 'Food', value: 950, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Lipa', scope: 'Scope 1', category: 'Fuel', value: 2100, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lipa', scope: 'Scope 1', category: 'LPG', value: 1050, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lipa', scope: 'Scope 2', category: 'Electricity', value: 6800, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lipa', scope: 'Scope 3', category: 'Water', value: 1600, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lipa', scope: 'Scope 3', category: 'Waste', value: 1100, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lipa', scope: 'Scope 3', category: 'Travel', value: 2700, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lipa', scope: 'Scope 3', category: 'Food', value: 1300, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Balayan', scope: 'Scope 1', category: 'Fuel', value: 850, unit: 'kg CO2e' },
    { year: 2021, campus: 'Balayan', scope: 'Scope 1', category: 'LPG', value: 425, unit: 'kg CO2e' },
    { year: 2021, campus: 'Balayan', scope: 'Scope 2', category: 'Electricity', value: 3150, unit: 'kg CO2e' },
    { year: 2021, campus: 'Balayan', scope: 'Scope 3', category: 'Water', value: 650, unit: 'kg CO2e' },
    { year: 2021, campus: 'Balayan', scope: 'Scope 3', category: 'Waste', value: 450, unit: 'kg CO2e' },
    { year: 2021, campus: 'Balayan', scope: 'Scope 3', category: 'Travel', value: 1000, unit: 'kg CO2e' },
    { year: 2021, campus: 'Balayan', scope: 'Scope 3', category: 'Food', value: 550, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Malvar', scope: 'Scope 1', category: 'Fuel', value: 950, unit: 'kg CO2e' },
    { year: 2021, campus: 'Malvar', scope: 'Scope 1', category: 'LPG', value: 475, unit: 'kg CO2e' },
    { year: 2021, campus: 'Malvar', scope: 'Scope 2', category: 'Electricity', value: 3350, unit: 'kg CO2e' },
    { year: 2021, campus: 'Malvar', scope: 'Scope 3', category: 'Water', value: 750, unit: 'kg CO2e' },
    { year: 2021, campus: 'Malvar', scope: 'Scope 3', category: 'Waste', value: 550, unit: 'kg CO2e' },
    { year: 2021, campus: 'Malvar', scope: 'Scope 3', category: 'Travel', value: 1200, unit: 'kg CO2e' },
    { year: 2021, campus: 'Malvar', scope: 'Scope 3', category: 'Food', value: 650, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Lemery', scope: 'Scope 1', category: 'Fuel', value: 1200, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lemery', scope: 'Scope 1', category: 'LPG', value: 600, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lemery', scope: 'Scope 2', category: 'Electricity', value: 4000, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lemery', scope: 'Scope 3', category: 'Water', value: 850, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lemery', scope: 'Scope 3', category: 'Waste', value: 650, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lemery', scope: 'Scope 3', category: 'Travel', value: 1400, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lemery', scope: 'Scope 3', category: 'Food', value: 750, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Lobo', scope: 'Scope 1', category: 'Fuel', value: 750, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lobo', scope: 'Scope 1', category: 'LPG', value: 375, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lobo', scope: 'Scope 2', category: 'Electricity', value: 2650, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lobo', scope: 'Scope 3', category: 'Water', value: 550, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lobo', scope: 'Scope 3', category: 'Waste', value: 350, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lobo', scope: 'Scope 3', category: 'Travel', value: 800, unit: 'kg CO2e' },
    { year: 2021, campus: 'Lobo', scope: 'Scope 3', category: 'Food', value: 450, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Nasugbu', scope: 'Scope 1', category: 'Fuel', value: 1400, unit: 'kg CO2e' },
    { year: 2021, campus: 'Nasugbu', scope: 'Scope 1', category: 'LPG', value: 700, unit: 'kg CO2e' },
    { year: 2021, campus: 'Nasugbu', scope: 'Scope 2', category: 'Electricity', value: 4400, unit: 'kg CO2e' },
    { year: 2021, campus: 'Nasugbu', scope: 'Scope 3', category: 'Water', value: 950, unit: 'kg CO2e' },
    { year: 2021, campus: 'Nasugbu', scope: 'Scope 3', category: 'Waste', value: 750, unit: 'kg CO2e' },
    { year: 2021, campus: 'Nasugbu', scope: 'Scope 3', category: 'Travel', value: 1800, unit: 'kg CO2e' },
    { year: 2021, campus: 'Nasugbu', scope: 'Scope 3', category: 'Food', value: 900, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Mabini', scope: 'Scope 1', category: 'Fuel', value: 1100, unit: 'kg CO2e' },
    { year: 2021, campus: 'Mabini', scope: 'Scope 1', category: 'LPG', value: 550, unit: 'kg CO2e' },
    { year: 2021, campus: 'Mabini', scope: 'Scope 2', category: 'Electricity', value: 3700, unit: 'kg CO2e' },
    { year: 2021, campus: 'Mabini', scope: 'Scope 3', category: 'Water', value: 800, unit: 'kg CO2e' },
    { year: 2021, campus: 'Mabini', scope: 'Scope 3', category: 'Waste', value: 600, unit: 'kg CO2e' },
    { year: 2021, campus: 'Mabini', scope: 'Scope 3', category: 'Travel', value: 1500, unit: 'kg CO2e' },
    { year: 2021, campus: 'Mabini', scope: 'Scope 3', category: 'Food', value: 750, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'Fuel', value: 900, unit: 'kg CO2e' },
    { year: 2021, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'LPG', value: 450, unit: 'kg CO2e' },
    { year: 2021, campus: 'Pablo Borbon', scope: 'Scope 2', category: 'Electricity', value: 3250, unit: 'kg CO2e' },
    { year: 2021, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Water', value: 700, unit: 'kg CO2e' },
    { year: 2021, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Waste', value: 500, unit: 'kg CO2e' },
    { year: 2021, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Travel', value: 1100, unit: 'kg CO2e' },
    { year: 2021, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Food', value: 600, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'Rosario', scope: 'Scope 1', category: 'Fuel', value: 1000, unit: 'kg CO2e' },
    { year: 2021, campus: 'Rosario', scope: 'Scope 1', category: 'LPG', value: 500, unit: 'kg CO2e' },
    { year: 2021, campus: 'Rosario', scope: 'Scope 2', category: 'Electricity', value: 3550, unit: 'kg CO2e' },
    { year: 2021, campus: 'Rosario', scope: 'Scope 3', category: 'Water', value: 750, unit: 'kg CO2e' },
    { year: 2021, campus: 'Rosario', scope: 'Scope 3', category: 'Waste', value: 550, unit: 'kg CO2e' },
    { year: 2021, campus: 'Rosario', scope: 'Scope 3', category: 'Travel', value: 1300, unit: 'kg CO2e' },
    { year: 2021, campus: 'Rosario', scope: 'Scope 3', category: 'Food', value: 700, unit: 'kg CO2e' },
    
    { year: 2021, campus: 'San Juan', scope: 'Scope 1', category: 'Fuel', value: 1200, unit: 'kg CO2e' },
    { year: 2021, campus: 'San Juan', scope: 'Scope 1', category: 'LPG', value: 600, unit: 'kg CO2e' },
    { year: 2021, campus: 'San Juan', scope: 'Scope 2', category: 'Electricity', value: 4100, unit: 'kg CO2e' },
    { year: 2021, campus: 'San Juan', scope: 'Scope 3', category: 'Water', value: 850, unit: 'kg CO2e' },
    { year: 2021, campus: 'San Juan', scope: 'Scope 3', category: 'Waste', value: 650, unit: 'kg CO2e' },
    { year: 2021, campus: 'San Juan', scope: 'Scope 3', category: 'Travel', value: 1650, unit: 'kg CO2e' },
    { year: 2021, campus: 'San Juan', scope: 'Scope 3', category: 'Food', value: 850, unit: 'kg CO2e' },
    
    // 2022 Data
    { year: 2022, campus: 'CSD', scope: 'Scope 1', category: 'Fuel', value: 1700, unit: 'kg CO2e' },
    { year: 2022, campus: 'CSD', scope: 'Scope 1', category: 'LPG', value: 900, unit: 'kg CO2e' },
    { year: 2022, campus: 'CSD', scope: 'Scope 2', category: 'Electricity', value: 5400, unit: 'kg CO2e' },
    { year: 2022, campus: 'CSD', scope: 'Scope 3', category: 'Water', value: 1400, unit: 'kg CO2e' },
    { year: 2022, campus: 'CSD', scope: 'Scope 3', category: 'Waste', value: 1000, unit: 'kg CO2e' },
    { year: 2022, campus: 'CSD', scope: 'Scope 3', category: 'Travel', value: 2500, unit: 'kg CO2e' },
    { year: 2022, campus: 'CSD', scope: 'Scope 3', category: 'Food', value: 1100, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Alangilan', scope: 'Scope 1', category: 'Fuel', value: 1400, unit: 'kg CO2e' },
    { year: 2022, campus: 'Alangilan', scope: 'Scope 1', category: 'LPG', value: 700, unit: 'kg CO2e' },
    { year: 2022, campus: 'Alangilan', scope: 'Scope 2', category: 'Electricity', value: 4900, unit: 'kg CO2e' },
    { year: 2022, campus: 'Alangilan', scope: 'Scope 3', category: 'Water', value: 1300, unit: 'kg CO2e' },
    { year: 2022, campus: 'Alangilan', scope: 'Scope 3', category: 'Waste', value: 950, unit: 'kg CO2e' },
    { year: 2022, campus: 'Alangilan', scope: 'Scope 3', category: 'Travel', value: 2200, unit: 'kg CO2e' },
    { year: 2022, campus: 'Alangilan', scope: 'Scope 3', category: 'Food', value: 1050, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Lipa', scope: 'Scope 1', category: 'Fuel', value: 2200, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lipa', scope: 'Scope 1', category: 'LPG', value: 1100, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lipa', scope: 'Scope 2', category: 'Electricity', value: 7100, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lipa', scope: 'Scope 3', category: 'Water', value: 1700, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lipa', scope: 'Scope 3', category: 'Waste', value: 1200, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lipa', scope: 'Scope 3', category: 'Travel', value: 2900, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lipa', scope: 'Scope 3', category: 'Food', value: 1400, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Balayan', scope: 'Scope 1', category: 'Fuel', value: 900, unit: 'kg CO2e' },
    { year: 2022, campus: 'Balayan', scope: 'Scope 1', category: 'LPG', value: 450, unit: 'kg CO2e' },
    { year: 2022, campus: 'Balayan', scope: 'Scope 2', category: 'Electricity', value: 3300, unit: 'kg CO2e' },
    { year: 2022, campus: 'Balayan', scope: 'Scope 3', category: 'Water', value: 700, unit: 'kg CO2e' },
    { year: 2022, campus: 'Balayan', scope: 'Scope 3', category: 'Waste', value: 500, unit: 'kg CO2e' },
    { year: 2022, campus: 'Balayan', scope: 'Scope 3', category: 'Travel', value: 1100, unit: 'kg CO2e' },
    { year: 2022, campus: 'Balayan', scope: 'Scope 3', category: 'Food', value: 600, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Malvar', scope: 'Scope 1', category: 'Fuel', value: 1050, unit: 'kg CO2e' },
    { year: 2022, campus: 'Malvar', scope: 'Scope 1', category: 'LPG', value: 525, unit: 'kg CO2e' },
    { year: 2022, campus: 'Malvar', scope: 'Scope 2', category: 'Electricity', value: 3500, unit: 'kg CO2e' },
    { year: 2022, campus: 'Malvar', scope: 'Scope 3', category: 'Water', value: 800, unit: 'kg CO2e' },
    { year: 2022, campus: 'Malvar', scope: 'Scope 3', category: 'Waste', value: 600, unit: 'kg CO2e' },
    { year: 2022, campus: 'Malvar', scope: 'Scope 3', category: 'Travel', value: 1300, unit: 'kg CO2e' },
    { year: 2022, campus: 'Malvar', scope: 'Scope 3', category: 'Food', value: 700, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Lemery', scope: 'Scope 1', category: 'Fuel', value: 1300, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lemery', scope: 'Scope 1', category: 'LPG', value: 650, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lemery', scope: 'Scope 2', category: 'Electricity', value: 4200, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lemery', scope: 'Scope 3', category: 'Water', value: 900, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lemery', scope: 'Scope 3', category: 'Waste', value: 700, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lemery', scope: 'Scope 3', category: 'Travel', value: 1600, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lemery', scope: 'Scope 3', category: 'Food', value: 850, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Lobo', scope: 'Scope 1', category: 'Fuel', value: 800, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lobo', scope: 'Scope 1', category: 'LPG', value: 400, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lobo', scope: 'Scope 2', category: 'Electricity', value: 2800, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lobo', scope: 'Scope 3', category: 'Water', value: 600, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lobo', scope: 'Scope 3', category: 'Waste', value: 400, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lobo', scope: 'Scope 3', category: 'Travel', value: 900, unit: 'kg CO2e' },
    { year: 2022, campus: 'Lobo', scope: 'Scope 3', category: 'Food', value: 500, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Nasugbu', scope: 'Scope 1', category: 'Fuel', value: 1500, unit: 'kg CO2e' },
    { year: 2022, campus: 'Nasugbu', scope: 'Scope 1', category: 'LPG', value: 750, unit: 'kg CO2e' },
    { year: 2022, campus: 'Nasugbu', scope: 'Scope 2', category: 'Electricity', value: 4600, unit: 'kg CO2e' },
    { year: 2022, campus: 'Nasugbu', scope: 'Scope 3', category: 'Water', value: 1000, unit: 'kg CO2e' },
    { year: 2022, campus: 'Nasugbu', scope: 'Scope 3', category: 'Waste', value: 800, unit: 'kg CO2e' },
    { year: 2022, campus: 'Nasugbu', scope: 'Scope 3', category: 'Travel', value: 2000, unit: 'kg CO2e' },
    { year: 2022, campus: 'Nasugbu', scope: 'Scope 3', category: 'Food', value: 1000, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Mabini', scope: 'Scope 1', category: 'Fuel', value: 1200, unit: 'kg CO2e' },
    { year: 2022, campus: 'Mabini', scope: 'Scope 1', category: 'LPG', value: 600, unit: 'kg CO2e' },
    { year: 2022, campus: 'Mabini', scope: 'Scope 2', category: 'Electricity', value: 3900, unit: 'kg CO2e' },
    { year: 2022, campus: 'Mabini', scope: 'Scope 3', category: 'Water', value: 850, unit: 'kg CO2e' },
    { year: 2022, campus: 'Mabini', scope: 'Scope 3', category: 'Waste', value: 650, unit: 'kg CO2e' },
    { year: 2022, campus: 'Mabini', scope: 'Scope 3', category: 'Travel', value: 1600, unit: 'kg CO2e' },
    { year: 2022, campus: 'Mabini', scope: 'Scope 3', category: 'Food', value: 800, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'Fuel', value: 1000, unit: 'kg CO2e' },
    { year: 2022, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'LPG', value: 500, unit: 'kg CO2e' },
    { year: 2022, campus: 'Pablo Borbon', scope: 'Scope 2', category: 'Electricity', value: 3400, unit: 'kg CO2e' },
    { year: 2022, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Water', value: 750, unit: 'kg CO2e' },
    { year: 2022, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Waste', value: 550, unit: 'kg CO2e' },
    { year: 2022, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Travel', value: 1200, unit: 'kg CO2e' },
    { year: 2022, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Food', value: 650, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'Rosario', scope: 'Scope 1', category: 'Fuel', value: 1100, unit: 'kg CO2e' },
    { year: 2022, campus: 'Rosario', scope: 'Scope 1', category: 'LPG', value: 550, unit: 'kg CO2e' },
    { year: 2022, campus: 'Rosario', scope: 'Scope 2', category: 'Electricity', value: 3700, unit: 'kg CO2e' },
    { year: 2022, campus: 'Rosario', scope: 'Scope 3', category: 'Water', value: 800, unit: 'kg CO2e' },
    { year: 2022, campus: 'Rosario', scope: 'Scope 3', category: 'Waste', value: 600, unit: 'kg CO2e' },
    { year: 2022, campus: 'Rosario', scope: 'Scope 3', category: 'Travel', value: 1400, unit: 'kg CO2e' },
    { year: 2022, campus: 'Rosario', scope: 'Scope 3', category: 'Food', value: 750, unit: 'kg CO2e' },
    
    { year: 2022, campus: 'San Juan', scope: 'Scope 1', category: 'Fuel', value: 1300, unit: 'kg CO2e' },
    { year: 2022, campus: 'San Juan', scope: 'Scope 1', category: 'LPG', value: 650, unit: 'kg CO2e' },
    { year: 2022, campus: 'San Juan', scope: 'Scope 2', category: 'Electricity', value: 4300, unit: 'kg CO2e' },
    { year: 2022, campus: 'San Juan', scope: 'Scope 3', category: 'Water', value: 900, unit: 'kg CO2e' },
    { year: 2022, campus: 'San Juan', scope: 'Scope 3', category: 'Waste', value: 700, unit: 'kg CO2e' },
    { year: 2022, campus: 'San Juan', scope: 'Scope 3', category: 'Travel', value: 1800, unit: 'kg CO2e' },
    { year: 2022, campus: 'San Juan', scope: 'Scope 3', category: 'Food', value: 950, unit: 'kg CO2e' },
    
    // 2023 Data
    { year: 2023, campus: 'CSD', scope: 'Scope 1', category: 'Fuel', value: 1750, unit: 'kg CO2e' },
    { year: 2023, campus: 'CSD', scope: 'Scope 1', category: 'LPG', value: 920, unit: 'kg CO2e' },
    { year: 2023, campus: 'CSD', scope: 'Scope 2', category: 'Electricity', value: 5600, unit: 'kg CO2e' },
    { year: 2023, campus: 'CSD', scope: 'Scope 3', category: 'Water', value: 1500, unit: 'kg CO2e' },
    { year: 2023, campus: 'CSD', scope: 'Scope 3', category: 'Waste', value: 1050, unit: 'kg CO2e' },
    { year: 2023, campus: 'CSD', scope: 'Scope 3', category: 'Travel', value: 2600, unit: 'kg CO2e' },
    { year: 2023, campus: 'CSD', scope: 'Scope 3', category: 'Food', value: 1150, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Alangilan', scope: 'Scope 1', category: 'Fuel', value: 1450, unit: 'kg CO2e' },
    { year: 2023, campus: 'Alangilan', scope: 'Scope 1', category: 'LPG', value: 720, unit: 'kg CO2e' },
    { year: 2023, campus: 'Alangilan', scope: 'Scope 2', category: 'Electricity', value: 5050, unit: 'kg CO2e' },
    { year: 2023, campus: 'Alangilan', scope: 'Scope 3', category: 'Water', value: 1350, unit: 'kg CO2e' },
    { year: 2023, campus: 'Alangilan', scope: 'Scope 3', category: 'Waste', value: 1000, unit: 'kg CO2e' },
    { year: 2023, campus: 'Alangilan', scope: 'Scope 3', category: 'Travel', value: 2300, unit: 'kg CO2e' },
    { year: 2023, campus: 'Alangilan', scope: 'Scope 3', category: 'Food', value: 1100, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Lipa', scope: 'Scope 1', category: 'Fuel', value: 2300, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lipa', scope: 'Scope 1', category: 'LPG', value: 1150, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lipa', scope: 'Scope 2', category: 'Electricity', value: 7300, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lipa', scope: 'Scope 3', category: 'Water', value: 1800, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lipa', scope: 'Scope 3', category: 'Waste', value: 1300, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lipa', scope: 'Scope 3', category: 'Travel', value: 3000, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lipa', scope: 'Scope 3', category: 'Food', value: 1500, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Balayan', scope: 'Scope 1', category: 'Fuel', value: 950, unit: 'kg CO2e' },
    { year: 2023, campus: 'Balayan', scope: 'Scope 1', category: 'LPG', value: 475, unit: 'kg CO2e' },
    { year: 2023, campus: 'Balayan', scope: 'Scope 2', category: 'Electricity', value: 3450, unit: 'kg CO2e' },
    { year: 2023, campus: 'Balayan', scope: 'Scope 3', category: 'Water', value: 750, unit: 'kg CO2e' },
    { year: 2023, campus: 'Balayan', scope: 'Scope 3', category: 'Waste', value: 550, unit: 'kg CO2e' },
    { year: 2023, campus: 'Balayan', scope: 'Scope 3', category: 'Travel', value: 1150, unit: 'kg CO2e' },
    { year: 2023, campus: 'Balayan', scope: 'Scope 3', category: 'Food', value: 650, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Malvar', scope: 'Scope 1', category: 'Fuel', value: 1100, unit: 'kg CO2e' },
    { year: 2023, campus: 'Malvar', scope: 'Scope 1', category: 'LPG', value: 550, unit: 'kg CO2e' },
    { year: 2023, campus: 'Malvar', scope: 'Scope 2', category: 'Electricity', value: 3650, unit: 'kg CO2e' },
    { year: 2023, campus: 'Malvar', scope: 'Scope 3', category: 'Water', value: 850, unit: 'kg CO2e' },
    { year: 2023, campus: 'Malvar', scope: 'Scope 3', category: 'Waste', value: 650, unit: 'kg CO2e' },
    { year: 2023, campus: 'Malvar', scope: 'Scope 3', category: 'Travel', value: 1400, unit: 'kg CO2e' },
    { year: 2023, campus: 'Malvar', scope: 'Scope 3', category: 'Food', value: 750, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Lemery', scope: 'Scope 1', category: 'Fuel', value: 1400, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lemery', scope: 'Scope 1', category: 'LPG', value: 700, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lemery', scope: 'Scope 2', category: 'Electricity', value: 4400, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lemery', scope: 'Scope 3', category: 'Water', value: 950, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lemery', scope: 'Scope 3', category: 'Waste', value: 750, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lemery', scope: 'Scope 3', category: 'Travel', value: 1700, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lemery', scope: 'Scope 3', category: 'Food', value: 900, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Lobo', scope: 'Scope 1', category: 'Fuel', value: 850, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lobo', scope: 'Scope 1', category: 'LPG', value: 425, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lobo', scope: 'Scope 2', category: 'Electricity', value: 2950, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lobo', scope: 'Scope 3', category: 'Water', value: 650, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lobo', scope: 'Scope 3', category: 'Waste', value: 450, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lobo', scope: 'Scope 3', category: 'Travel', value: 950, unit: 'kg CO2e' },
    { year: 2023, campus: 'Lobo', scope: 'Scope 3', category: 'Food', value: 550, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Nasugbu', scope: 'Scope 1', category: 'Fuel', value: 1600, unit: 'kg CO2e' },
    { year: 2023, campus: 'Nasugbu', scope: 'Scope 1', category: 'LPG', value: 800, unit: 'kg CO2e' },
    { year: 2023, campus: 'Nasugbu', scope: 'Scope 2', category: 'Electricity', value: 4800, unit: 'kg CO2e' },
    { year: 2023, campus: 'Nasugbu', scope: 'Scope 3', category: 'Water', value: 1050, unit: 'kg CO2e' },
    { year: 2023, campus: 'Nasugbu', scope: 'Scope 3', category: 'Waste', value: 850, unit: 'kg CO2e' },
    { year: 2023, campus: 'Nasugbu', scope: 'Scope 3', category: 'Travel', value: 2100, unit: 'kg CO2e' },
    { year: 2023, campus: 'Nasugbu', scope: 'Scope 3', category: 'Food', value: 1050, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Mabini', scope: 'Scope 1', category: 'Fuel', value: 1300, unit: 'kg CO2e' },
    { year: 2023, campus: 'Mabini', scope: 'Scope 1', category: 'LPG', value: 650, unit: 'kg CO2e' },
    { year: 2023, campus: 'Mabini', scope: 'Scope 2', category: 'Electricity', value: 4100, unit: 'kg CO2e' },
    { year: 2023, campus: 'Mabini', scope: 'Scope 3', category: 'Water', value: 900, unit: 'kg CO2e' },
    { year: 2023, campus: 'Mabini', scope: 'Scope 3', category: 'Waste', value: 700, unit: 'kg CO2e' },
    { year: 2023, campus: 'Mabini', scope: 'Scope 3', category: 'Travel', value: 1700, unit: 'kg CO2e' },
    { year: 2023, campus: 'Mabini', scope: 'Scope 3', category: 'Food', value: 850, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'Fuel', value: 1100, unit: 'kg CO2e' },
    { year: 2023, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'LPG', value: 550, unit: 'kg CO2e' },
    { year: 2023, campus: 'Pablo Borbon', scope: 'Scope 2', category: 'Electricity', value: 3550, unit: 'kg CO2e' },
    { year: 2023, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Water', value: 800, unit: 'kg CO2e' },
    { year: 2023, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Waste', value: 600, unit: 'kg CO2e' },
    { year: 2023, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Travel', value: 1300, unit: 'kg CO2e' },
    { year: 2023, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Food', value: 700, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'Rosario', scope: 'Scope 1', category: 'Fuel', value: 1200, unit: 'kg CO2e' },
    { year: 2023, campus: 'Rosario', scope: 'Scope 1', category: 'LPG', value: 600, unit: 'kg CO2e' },
    { year: 2023, campus: 'Rosario', scope: 'Scope 2', category: 'Electricity', value: 3850, unit: 'kg CO2e' },
    { year: 2023, campus: 'Rosario', scope: 'Scope 3', category: 'Water', value: 850, unit: 'kg CO2e' },
    { year: 2023, campus: 'Rosario', scope: 'Scope 3', category: 'Waste', value: 650, unit: 'kg CO2e' },
    { year: 2023, campus: 'Rosario', scope: 'Scope 3', category: 'Travel', value: 1500, unit: 'kg CO2e' },
    { year: 2023, campus: 'Rosario', scope: 'Scope 3', category: 'Food', value: 800, unit: 'kg CO2e' },
    
    { year: 2023, campus: 'San Juan', scope: 'Scope 1', category: 'Fuel', value: 1400, unit: 'kg CO2e' },
    { year: 2023, campus: 'San Juan', scope: 'Scope 1', category: 'LPG', value: 700, unit: 'kg CO2e' },
    { year: 2023, campus: 'San Juan', scope: 'Scope 2', category: 'Electricity', value: 4500, unit: 'kg CO2e' },
    { year: 2023, campus: 'San Juan', scope: 'Scope 3', category: 'Water', value: 950, unit: 'kg CO2e' },
    { year: 2023, campus: 'San Juan', scope: 'Scope 3', category: 'Waste', value: 750, unit: 'kg CO2e' },
    { year: 2023, campus: 'San Juan', scope: 'Scope 3', category: 'Travel', value: 1900, unit: 'kg CO2e' },
    { year: 2023, campus: 'San Juan', scope: 'Scope 3', category: 'Food', value: 1000, unit: 'kg CO2e' },
    
    // 2024 Data
    { year: 2024, campus: 'CSD', scope: 'Scope 1', category: 'Fuel', value: 1750, unit: 'kg CO2e' },
    { year: 2024, campus: 'CSD', scope: 'Scope 1', category: 'LPG', value: 950, unit: 'kg CO2e' },
    { year: 2024, campus: 'CSD', scope: 'Scope 2', category: 'Electricity', value: 5700, unit: 'kg CO2e' },
    { year: 2024, campus: 'CSD', scope: 'Scope 3', category: 'Water', value: 1550, unit: 'kg CO2e' },
    { year: 2024, campus: 'CSD', scope: 'Scope 3', category: 'Waste', value: 1100, unit: 'kg CO2e' },
    { year: 2024, campus: 'CSD', scope: 'Scope 3', category: 'Travel', value: 2700, unit: 'kg CO2e' },
    { year: 2024, campus: 'CSD', scope: 'Scope 3', category: 'Food', value: 1200, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Alangilan', scope: 'Scope 1', category: 'Fuel', value: 1500, unit: 'kg CO2e' },
    { year: 2024, campus: 'Alangilan', scope: 'Scope 1', category: 'LPG', value: 750, unit: 'kg CO2e' },
    { year: 2024, campus: 'Alangilan', scope: 'Scope 2', category: 'Electricity', value: 5200, unit: 'kg CO2e' },
    { year: 2024, campus: 'Alangilan', scope: 'Scope 3', category: 'Water', value: 1400, unit: 'kg CO2e' },
    { year: 2024, campus: 'Alangilan', scope: 'Scope 3', category: 'Waste', value: 1050, unit: 'kg CO2e' },
    { year: 2024, campus: 'Alangilan', scope: 'Scope 3', category: 'Travel', value: 2400, unit: 'kg CO2e' },
    { year: 2024, campus: 'Alangilan', scope: 'Scope 3', category: 'Food', value: 1150, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Lipa', scope: 'Scope 1', category: 'Fuel', value: 2350, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lipa', scope: 'Scope 1', category: 'LPG', value: 1200, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lipa', scope: 'Scope 2', category: 'Electricity', value: 7500, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lipa', scope: 'Scope 3', category: 'Water', value: 1850, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lipa', scope: 'Scope 3', category: 'Waste', value: 1350, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lipa', scope: 'Scope 3', category: 'Travel', value: 3100, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lipa', scope: 'Scope 3', category: 'Food', value: 1550, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Balayan', scope: 'Scope 1', category: 'Fuel', value: 1000, unit: 'kg CO2e' },
    { year: 2024, campus: 'Balayan', scope: 'Scope 1', category: 'LPG', value: 500, unit: 'kg CO2e' },
    { year: 2024, campus: 'Balayan', scope: 'Scope 2', category: 'Electricity', value: 3600, unit: 'kg CO2e' },
    { year: 2024, campus: 'Balayan', scope: 'Scope 3', category: 'Water', value: 800, unit: 'kg CO2e' },
    { year: 2024, campus: 'Balayan', scope: 'Scope 3', category: 'Waste', value: 600, unit: 'kg CO2e' },
    { year: 2024, campus: 'Balayan', scope: 'Scope 3', category: 'Travel', value: 1200, unit: 'kg CO2e' },
    { year: 2024, campus: 'Balayan', scope: 'Scope 3', category: 'Food', value: 700, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Malvar', scope: 'Scope 1', category: 'Fuel', value: 1150, unit: 'kg CO2e' },
    { year: 2024, campus: 'Malvar', scope: 'Scope 1', category: 'LPG', value: 575, unit: 'kg CO2e' },
    { year: 2024, campus: 'Malvar', scope: 'Scope 2', category: 'Electricity', value: 3800, unit: 'kg CO2e' },
    { year: 2024, campus: 'Malvar', scope: 'Scope 3', category: 'Water', value: 900, unit: 'kg CO2e' },
    { year: 2024, campus: 'Malvar', scope: 'Scope 3', category: 'Waste', value: 700, unit: 'kg CO2e' },
    { year: 2024, campus: 'Malvar', scope: 'Scope 3', category: 'Travel', value: 1500, unit: 'kg CO2e' },
    { year: 2024, campus: 'Malvar', scope: 'Scope 3', category: 'Food', value: 800, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Lemery', scope: 'Scope 1', category: 'Fuel', value: 1450, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lemery', scope: 'Scope 1', category: 'LPG', value: 725, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lemery', scope: 'Scope 2', category: 'Electricity', value: 4600, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lemery', scope: 'Scope 3', category: 'Water', value: 1000, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lemery', scope: 'Scope 3', category: 'Waste', value: 800, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lemery', scope: 'Scope 3', category: 'Travel', value: 1800, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lemery', scope: 'Scope 3', category: 'Food', value: 950, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Lobo', scope: 'Scope 1', category: 'Fuel', value: 900, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lobo', scope: 'Scope 1', category: 'LPG', value: 450, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lobo', scope: 'Scope 2', category: 'Electricity', value: 3100, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lobo', scope: 'Scope 3', category: 'Water', value: 700, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lobo', scope: 'Scope 3', category: 'Waste', value: 500, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lobo', scope: 'Scope 3', category: 'Travel', value: 1000, unit: 'kg CO2e' },
    { year: 2024, campus: 'Lobo', scope: 'Scope 3', category: 'Food', value: 600, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Nasugbu', scope: 'Scope 1', category: 'Fuel', value: 1700, unit: 'kg CO2e' },
    { year: 2024, campus: 'Nasugbu', scope: 'Scope 1', category: 'LPG', value: 850, unit: 'kg CO2e' },
    { year: 2024, campus: 'Nasugbu', scope: 'Scope 2', category: 'Electricity', value: 5000, unit: 'kg CO2e' },
    { year: 2024, campus: 'Nasugbu', scope: 'Scope 3', category: 'Water', value: 1100, unit: 'kg CO2e' },
    { year: 2024, campus: 'Nasugbu', scope: 'Scope 3', category: 'Waste', value: 900, unit: 'kg CO2e' },
    { year: 2024, campus: 'Nasugbu', scope: 'Scope 3', category: 'Travel', value: 2200, unit: 'kg CO2e' },
    { year: 2024, campus: 'Nasugbu', scope: 'Scope 3', category: 'Food', value: 1100, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Mabini', scope: 'Scope 1', category: 'Fuel', value: 1400, unit: 'kg CO2e' },
    { year: 2024, campus: 'Mabini', scope: 'Scope 1', category: 'LPG', value: 700, unit: 'kg CO2e' },
    { year: 2024, campus: 'Mabini', scope: 'Scope 2', category: 'Electricity', value: 4300, unit: 'kg CO2e' },
    { year: 2024, campus: 'Mabini', scope: 'Scope 3', category: 'Water', value: 950, unit: 'kg CO2e' },
    { year: 2024, campus: 'Mabini', scope: 'Scope 3', category: 'Waste', value: 750, unit: 'kg CO2e' },
    { year: 2024, campus: 'Mabini', scope: 'Scope 3', category: 'Travel', value: 1800, unit: 'kg CO2e' },
    { year: 2024, campus: 'Mabini', scope: 'Scope 3', category: 'Food', value: 900, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'Fuel', value: 1200, unit: 'kg CO2e' },
    { year: 2024, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'LPG', value: 600, unit: 'kg CO2e' },
    { year: 2024, campus: 'Pablo Borbon', scope: 'Scope 2', category: 'Electricity', value: 3700, unit: 'kg CO2e' },
    { year: 2024, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Water', value: 850, unit: 'kg CO2e' },
    { year: 2024, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Waste', value: 650, unit: 'kg CO2e' },
    { year: 2024, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Travel', value: 1400, unit: 'kg CO2e' },
    { year: 2024, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Food', value: 750, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'Rosario', scope: 'Scope 1', category: 'Fuel', value: 1300, unit: 'kg CO2e' },
    { year: 2024, campus: 'Rosario', scope: 'Scope 1', category: 'LPG', value: 650, unit: 'kg CO2e' },
    { year: 2024, campus: 'Rosario', scope: 'Scope 2', category: 'Electricity', value: 4000, unit: 'kg CO2e' },
    { year: 2024, campus: 'Rosario', scope: 'Scope 3', category: 'Water', value: 900, unit: 'kg CO2e' },
    { year: 2024, campus: 'Rosario', scope: 'Scope 3', category: 'Waste', value: 700, unit: 'kg CO2e' },
    { year: 2024, campus: 'Rosario', scope: 'Scope 3', category: 'Travel', value: 1600, unit: 'kg CO2e' },
    { year: 2024, campus: 'Rosario', scope: 'Scope 3', category: 'Food', value: 850, unit: 'kg CO2e' },
    
    { year: 2024, campus: 'San Juan', scope: 'Scope 1', category: 'Fuel', value: 1500, unit: 'kg CO2e' },
    { year: 2024, campus: 'San Juan', scope: 'Scope 1', category: 'LPG', value: 750, unit: 'kg CO2e' },
    { year: 2024, campus: 'San Juan', scope: 'Scope 2', category: 'Electricity', value: 4700, unit: 'kg CO2e' },
    { year: 2024, campus: 'San Juan', scope: 'Scope 3', category: 'Water', value: 1000, unit: 'kg CO2e' },
    { year: 2024, campus: 'San Juan', scope: 'Scope 3', category: 'Waste', value: 800, unit: 'kg CO2e' },
    { year: 2024, campus: 'San Juan', scope: 'Scope 3', category: 'Travel', value: 2000, unit: 'kg CO2e' },
    { year: 2024, campus: 'San Juan', scope: 'Scope 3', category: 'Food', value: 1050, unit: 'kg CO2e' },
    
    // 2025 Data
    { year: 2025, campus: 'CSD', scope: 'Scope 1', category: 'Fuel', value: 1800, unit: 'kg CO2e' },
    { year: 2025, campus: 'CSD', scope: 'Scope 1', category: 'LPG', value: 950, unit: 'kg CO2e' },
    { year: 2025, campus: 'CSD', scope: 'Scope 2', category: 'Electricity', value: 5800, unit: 'kg CO2e' },
    { year: 2025, campus: 'CSD', scope: 'Scope 3', category: 'Water', value: 1600, unit: 'kg CO2e' },
    { year: 2025, campus: 'CSD', scope: 'Scope 3', category: 'Waste', value: 1150, unit: 'kg CO2e' },
    { year: 2025, campus: 'CSD', scope: 'Scope 3', category: 'Travel', value: 2800, unit: 'kg CO2e' },
    { year: 2025, campus: 'CSD', scope: 'Scope 3', category: 'Food', value: 1250, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Alangilan', scope: 'Scope 1', category: 'Fuel', value: 1550, unit: 'kg CO2e' },
    { year: 2025, campus: 'Alangilan', scope: 'Scope 1', category: 'LPG', value: 775, unit: 'kg CO2e' },
    { year: 2025, campus: 'Alangilan', scope: 'Scope 2', category: 'Electricity', value: 5350, unit: 'kg CO2e' },
    { year: 2025, campus: 'Alangilan', scope: 'Scope 3', category: 'Water', value: 1450, unit: 'kg CO2e' },
    { year: 2025, campus: 'Alangilan', scope: 'Scope 3', category: 'Waste', value: 1100, unit: 'kg CO2e' },
    { year: 2025, campus: 'Alangilan', scope: 'Scope 3', category: 'Travel', value: 2500, unit: 'kg CO2e' },
    { year: 2025, campus: 'Alangilan', scope: 'Scope 3', category: 'Food', value: 1200, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Lipa', scope: 'Scope 1', category: 'Fuel', value: 2400, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lipa', scope: 'Scope 1', category: 'LPG', value: 1250, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lipa', scope: 'Scope 2', category: 'Electricity', value: 7650, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lipa', scope: 'Scope 3', category: 'Water', value: 1900, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lipa', scope: 'Scope 3', category: 'Waste', value: 1400, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lipa', scope: 'Scope 3', category: 'Travel', value: 3200, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lipa', scope: 'Scope 3', category: 'Food', value: 1600, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Balayan', scope: 'Scope 1', category: 'Fuel', value: 1050, unit: 'kg CO2e' },
    { year: 2025, campus: 'Balayan', scope: 'Scope 1', category: 'LPG', value: 525, unit: 'kg CO2e' },
    { year: 2025, campus: 'Balayan', scope: 'Scope 2', category: 'Electricity', value: 3750, unit: 'kg CO2e' },
    { year: 2025, campus: 'Balayan', scope: 'Scope 3', category: 'Water', value: 850, unit: 'kg CO2e' },
    { year: 2025, campus: 'Balayan', scope: 'Scope 3', category: 'Waste', value: 650, unit: 'kg CO2e' },
    { year: 2025, campus: 'Balayan', scope: 'Scope 3', category: 'Travel', value: 1300, unit: 'kg CO2e' },
    { year: 2025, campus: 'Balayan', scope: 'Scope 3', category: 'Food', value: 750, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Malvar', scope: 'Scope 1', category: 'Fuel', value: 1200, unit: 'kg CO2e' },
    { year: 2025, campus: 'Malvar', scope: 'Scope 1', category: 'LPG', value: 600, unit: 'kg CO2e' },
    { year: 2025, campus: 'Malvar', scope: 'Scope 2', category: 'Electricity', value: 3950, unit: 'kg CO2e' },
    { year: 2025, campus: 'Malvar', scope: 'Scope 3', category: 'Water', value: 950, unit: 'kg CO2e' },
    { year: 2025, campus: 'Malvar', scope: 'Scope 3', category: 'Waste', value: 750, unit: 'kg CO2e' },
    { year: 2025, campus: 'Malvar', scope: 'Scope 3', category: 'Travel', value: 1600, unit: 'kg CO2e' },
    { year: 2025, campus: 'Malvar', scope: 'Scope 3', category: 'Food', value: 850, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Lemery', scope: 'Scope 1', category: 'Fuel', value: 1500, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lemery', scope: 'Scope 1', category: 'LPG', value: 750, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lemery', scope: 'Scope 2', category: 'Electricity', value: 4750, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lemery', scope: 'Scope 3', category: 'Water', value: 1050, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lemery', scope: 'Scope 3', category: 'Waste', value: 850, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lemery', scope: 'Scope 3', category: 'Travel', value: 1900, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lemery', scope: 'Scope 3', category: 'Food', value: 1000, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Lobo', scope: 'Scope 1', category: 'Fuel', value: 950, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lobo', scope: 'Scope 1', category: 'LPG', value: 475, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lobo', scope: 'Scope 2', category: 'Electricity', value: 3250, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lobo', scope: 'Scope 3', category: 'Water', value: 750, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lobo', scope: 'Scope 3', category: 'Waste', value: 550, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lobo', scope: 'Scope 3', category: 'Travel', value: 1100, unit: 'kg CO2e' },
    { year: 2025, campus: 'Lobo', scope: 'Scope 3', category: 'Food', value: 650, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Nasugbu', scope: 'Scope 1', category: 'Fuel', value: 1800, unit: 'kg CO2e' },
    { year: 2025, campus: 'Nasugbu', scope: 'Scope 1', category: 'LPG', value: 900, unit: 'kg CO2e' },
    { year: 2025, campus: 'Nasugbu', scope: 'Scope 2', category: 'Electricity', value: 5200, unit: 'kg CO2e' },
    { year: 2025, campus: 'Nasugbu', scope: 'Scope 3', category: 'Water', value: 1150, unit: 'kg CO2e' },
    { year: 2025, campus: 'Nasugbu', scope: 'Scope 3', category: 'Waste', value: 950, unit: 'kg CO2e' },
    { year: 2025, campus: 'Nasugbu', scope: 'Scope 3', category: 'Travel', value: 2300, unit: 'kg CO2e' },
    { year: 2025, campus: 'Nasugbu', scope: 'Scope 3', category: 'Food', value: 1150, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Mabini', scope: 'Scope 1', category: 'Fuel', value: 1500, unit: 'kg CO2e' },
    { year: 2025, campus: 'Mabini', scope: 'Scope 1', category: 'LPG', value: 750, unit: 'kg CO2e' },
    { year: 2025, campus: 'Mabini', scope: 'Scope 2', category: 'Electricity', value: 4500, unit: 'kg CO2e' },
    { year: 2025, campus: 'Mabini', scope: 'Scope 3', category: 'Water', value: 1000, unit: 'kg CO2e' },
    { year: 2025, campus: 'Mabini', scope: 'Scope 3', category: 'Waste', value: 800, unit: 'kg CO2e' },
    { year: 2025, campus: 'Mabini', scope: 'Scope 3', category: 'Travel', value: 1900, unit: 'kg CO2e' },
    { year: 2025, campus: 'Mabini', scope: 'Scope 3', category: 'Food', value: 950, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'Fuel', value: 1300, unit: 'kg CO2e' },
    { year: 2025, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'LPG', value: 650, unit: 'kg CO2e' },
    { year: 2025, campus: 'Pablo Borbon', scope: 'Scope 2', category: 'Electricity', value: 3850, unit: 'kg CO2e' },
    { year: 2025, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Water', value: 900, unit: 'kg CO2e' },
    { year: 2025, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Waste', value: 700, unit: 'kg CO2e' },
    { year: 2025, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Travel', value: 1500, unit: 'kg CO2e' },
    { year: 2025, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Food', value: 800, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'Rosario', scope: 'Scope 1', category: 'Fuel', value: 1400, unit: 'kg CO2e' },
    { year: 2025, campus: 'Rosario', scope: 'Scope 1', category: 'LPG', value: 700, unit: 'kg CO2e' },
    { year: 2025, campus: 'Rosario', scope: 'Scope 2', category: 'Electricity', value: 4150, unit: 'kg CO2e' },
    { year: 2025, campus: 'Rosario', scope: 'Scope 3', category: 'Water', value: 950, unit: 'kg CO2e' },
    { year: 2025, campus: 'Rosario', scope: 'Scope 3', category: 'Waste', value: 750, unit: 'kg CO2e' },
    { year: 2025, campus: 'Rosario', scope: 'Scope 3', category: 'Travel', value: 1700, unit: 'kg CO2e' },
    { year: 2025, campus: 'Rosario', scope: 'Scope 3', category: 'Food', value: 900, unit: 'kg CO2e' },
    
    { year: 2025, campus: 'San Juan', scope: 'Scope 1', category: 'Fuel', value: 1600, unit: 'kg CO2e' },
    { year: 2025, campus: 'San Juan', scope: 'Scope 1', category: 'LPG', value: 800, unit: 'kg CO2e' },
    { year: 2025, campus: 'San Juan', scope: 'Scope 2', category: 'Electricity', value: 4900, unit: 'kg CO2e' },
    { year: 2025, campus: 'San Juan', scope: 'Scope 3', category: 'Water', value: 1050, unit: 'kg CO2e' },
    { year: 2025, campus: 'San Juan', scope: 'Scope 3', category: 'Waste', value: 850, unit: 'kg CO2e' },
    { year: 2025, campus: 'San Juan', scope: 'Scope 3', category: 'Travel', value: 2100, unit: 'kg CO2e' },
    { year: 2025, campus: 'San Juan', scope: 'Scope 3', category: 'Food', value: 1100, unit: 'kg CO2e' },
    
    // 2026 Data
    { year: 2026, campus: 'CSD', scope: 'Scope 1', category: 'Fuel', value: 1850, unit: 'kg CO2e' },
    { year: 2026, campus: 'CSD', scope: 'Scope 1', category: 'LPG', value: 975, unit: 'kg CO2e' },
    { year: 2026, campus: 'CSD', scope: 'Scope 2', category: 'Electricity', value: 5900, unit: 'kg CO2e' },
    { year: 2026, campus: 'CSD', scope: 'Scope 3', category: 'Water', value: 1650, unit: 'kg CO2e' },
    { year: 2026, campus: 'CSD', scope: 'Scope 3', category: 'Waste', value: 1200, unit: 'kg CO2e' },
    { year: 2026, campus: 'CSD', scope: 'Scope 3', category: 'Travel', value: 2900, unit: 'kg CO2e' },
    { year: 2026, campus: 'CSD', scope: 'Scope 3', category: 'Food', value: 1300, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Alangilan', scope: 'Scope 1', category: 'Fuel', value: 1600, unit: 'kg CO2e' },
    { year: 2026, campus: 'Alangilan', scope: 'Scope 1', category: 'LPG', value: 800, unit: 'kg CO2e' },
    { year: 2026, campus: 'Alangilan', scope: 'Scope 2', category: 'Electricity', value: 5500, unit: 'kg CO2e' },
    { year: 2026, campus: 'Alangilan', scope: 'Scope 3', category: 'Water', value: 1500, unit: 'kg CO2e' },
    { year: 2026, campus: 'Alangilan', scope: 'Scope 3', category: 'Waste', value: 1150, unit: 'kg CO2e' },
    { year: 2026, campus: 'Alangilan', scope: 'Scope 3', category: 'Travel', value: 2600, unit: 'kg CO2e' },
    { year: 2026, campus: 'Alangilan', scope: 'Scope 3', category: 'Food', value: 1250, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Lipa', scope: 'Scope 1', category: 'Fuel', value: 2450, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lipa', scope: 'Scope 1', category: 'LPG', value: 1275, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lipa', scope: 'Scope 2', category: 'Electricity', value: 7800, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lipa', scope: 'Scope 3', category: 'Water', value: 1950, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lipa', scope: 'Scope 3', category: 'Waste', value: 1450, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lipa', scope: 'Scope 3', category: 'Travel', value: 3300, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lipa', scope: 'Scope 3', category: 'Food', value: 1650, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Balayan', scope: 'Scope 1', category: 'Fuel', value: 1100, unit: 'kg CO2e' },
    { year: 2026, campus: 'Balayan', scope: 'Scope 1', category: 'LPG', value: 550, unit: 'kg CO2e' },
    { year: 2026, campus: 'Balayan', scope: 'Scope 2', category: 'Electricity', value: 3900, unit: 'kg CO2e' },
    { year: 2026, campus: 'Balayan', scope: 'Scope 3', category: 'Water', value: 900, unit: 'kg CO2e' },
    { year: 2026, campus: 'Balayan', scope: 'Scope 3', category: 'Waste', value: 700, unit: 'kg CO2e' },
    { year: 2026, campus: 'Balayan', scope: 'Scope 3', category: 'Travel', value: 1400, unit: 'kg CO2e' },
    { year: 2026, campus: 'Balayan', scope: 'Scope 3', category: 'Food', value: 800, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Malvar', scope: 'Scope 1', category: 'Fuel', value: 1250, unit: 'kg CO2e' },
    { year: 2026, campus: 'Malvar', scope: 'Scope 1', category: 'LPG', value: 625, unit: 'kg CO2e' },
    { year: 2026, campus: 'Malvar', scope: 'Scope 2', category: 'Electricity', value: 4100, unit: 'kg CO2e' },
    { year: 2026, campus: 'Malvar', scope: 'Scope 3', category: 'Water', value: 1000, unit: 'kg CO2e' },
    { year: 2026, campus: 'Malvar', scope: 'Scope 3', category: 'Waste', value: 800, unit: 'kg CO2e' },
    { year: 2026, campus: 'Malvar', scope: 'Scope 3', category: 'Travel', value: 1700, unit: 'kg CO2e' },
    { year: 2026, campus: 'Malvar', scope: 'Scope 3', category: 'Food', value: 900, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Lemery', scope: 'Scope 1', category: 'Fuel', value: 1550, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lemery', scope: 'Scope 1', category: 'LPG', value: 775, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lemery', scope: 'Scope 2', category: 'Electricity', value: 4900, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lemery', scope: 'Scope 3', category: 'Water', value: 1100, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lemery', scope: 'Scope 3', category: 'Waste', value: 900, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lemery', scope: 'Scope 3', category: 'Travel', value: 2000, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lemery', scope: 'Scope 3', category: 'Food', value: 1050, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Lobo', scope: 'Scope 1', category: 'Fuel', value: 1000, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lobo', scope: 'Scope 1', category: 'LPG', value: 500, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lobo', scope: 'Scope 2', category: 'Electricity', value: 3400, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lobo', scope: 'Scope 3', category: 'Water', value: 800, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lobo', scope: 'Scope 3', category: 'Waste', value: 600, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lobo', scope: 'Scope 3', category: 'Travel', value: 1200, unit: 'kg CO2e' },
    { year: 2026, campus: 'Lobo', scope: 'Scope 3', category: 'Food', value: 700, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Nasugbu', scope: 'Scope 1', category: 'Fuel', value: 1900, unit: 'kg CO2e' },
    { year: 2026, campus: 'Nasugbu', scope: 'Scope 1', category: 'LPG', value: 950, unit: 'kg CO2e' },
    { year: 2026, campus: 'Nasugbu', scope: 'Scope 2', category: 'Electricity', value: 5400, unit: 'kg CO2e' },
    { year: 2026, campus: 'Nasugbu', scope: 'Scope 3', category: 'Water', value: 1200, unit: 'kg CO2e' },
    { year: 2026, campus: 'Nasugbu', scope: 'Scope 3', category: 'Waste', value: 1000, unit: 'kg CO2e' },
    { year: 2026, campus: 'Nasugbu', scope: 'Scope 3', category: 'Travel', value: 2400, unit: 'kg CO2e' },
    { year: 2026, campus: 'Nasugbu', scope: 'Scope 3', category: 'Food', value: 1200, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Mabini', scope: 'Scope 1', category: 'Fuel', value: 1600, unit: 'kg CO2e' },
    { year: 2026, campus: 'Mabini', scope: 'Scope 1', category: 'LPG', value: 800, unit: 'kg CO2e' },
    { year: 2026, campus: 'Mabini', scope: 'Scope 2', category: 'Electricity', value: 4700, unit: 'kg CO2e' },
    { year: 2026, campus: 'Mabini', scope: 'Scope 3', category: 'Water', value: 1050, unit: 'kg CO2e' },
    { year: 2026, campus: 'Mabini', scope: 'Scope 3', category: 'Waste', value: 850, unit: 'kg CO2e' },
    { year: 2026, campus: 'Mabini', scope: 'Scope 3', category: 'Travel', value: 2000, unit: 'kg CO2e' },
    { year: 2026, campus: 'Mabini', scope: 'Scope 3', category: 'Food', value: 1000, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'Fuel', value: 1400, unit: 'kg CO2e' },
    { year: 2026, campus: 'Pablo Borbon', scope: 'Scope 1', category: 'LPG', value: 700, unit: 'kg CO2e' },
    { year: 2026, campus: 'Pablo Borbon', scope: 'Scope 2', category: 'Electricity', value: 4000, unit: 'kg CO2e' },
    { year: 2026, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Water', value: 950, unit: 'kg CO2e' },
    { year: 2026, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Waste', value: 750, unit: 'kg CO2e' },
    { year: 2026, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Travel', value: 1600, unit: 'kg CO2e' },
    { year: 2026, campus: 'Pablo Borbon', scope: 'Scope 3', category: 'Food', value: 850, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'Rosario', scope: 'Scope 1', category: 'Fuel', value: 1500, unit: 'kg CO2e' },
    { year: 2026, campus: 'Rosario', scope: 'Scope 1', category: 'LPG', value: 750, unit: 'kg CO2e' },
    { year: 2026, campus: 'Rosario', scope: 'Scope 2', category: 'Electricity', value: 4300, unit: 'kg CO2e' },
    { year: 2026, campus: 'Rosario', scope: 'Scope 3', category: 'Water', value: 1000, unit: 'kg CO2e' },
    { year: 2026, campus: 'Rosario', scope: 'Scope 3', category: 'Waste', value: 800, unit: 'kg CO2e' },
    { year: 2026, campus: 'Rosario', scope: 'Scope 3', category: 'Travel', value: 1800, unit: 'kg CO2e' },
    { year: 2026, campus: 'Rosario', scope: 'Scope 3', category: 'Food', value: 950, unit: 'kg CO2e' },
    
    { year: 2026, campus: 'San Juan', scope: 'Scope 1', category: 'Fuel', value: 1700, unit: 'kg CO2e' },
    { year: 2026, campus: 'San Juan', scope: 'Scope 1', category: 'LPG', value: 850, unit: 'kg CO2e' },
    { year: 2026, campus: 'San Juan', scope: 'Scope 2', category: 'Electricity', value: 5100, unit: 'kg CO2e' },
    { year: 2026, campus: 'San Juan', scope: 'Scope 3', category: 'Water', value: 1100, unit: 'kg CO2e' },
    { year: 2026, campus: 'San Juan', scope: 'Scope 3', category: 'Waste', value: 900, unit: 'kg CO2e' },
    { year: 2026, campus: 'San Juan', scope: 'Scope 3', category: 'Travel', value: 2200, unit: 'kg CO2e' },
    { year: 2026, campus: 'San Juan', scope: 'Scope 3', category: 'Food', value: 1150, unit: 'kg CO2e' }
];
